// <auto-generated />
using mentorient_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace mentorientapi.Migrations
{
    [DbContext(typeof(MentorientContext))]
    [Migration("20171003000432_Initil")]
    partial class Initil
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mentorient_api.Models.Mentor", b =>
                {
                    b.Property<int>("MentorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FristName");

                    b.Property<string>("LastName");

                    b.HasKey("MentorId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("mentorient_api.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("MentorId");

                    b.Property<string>("Title");

                    b.HasKey("VideoId");

                    b.HasIndex("MentorId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("mentorient_api.Models.Video", b =>
                {
                    b.HasOne("mentorient_api.Models.Mentor", "Mentor")
                        .WithMany("Videos")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
